load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "basic-app",
    srcs= ["basic-app/basic_dep.C"],
    hdrs = ["basic-app/basic_dep.H"],
    includes = ["."],
    visibility = ["//visibility:public"]
)